# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 855b2b22a82bc4bcb2a44d059de21c48e4eca7f835bfb116718aaedf3f6b551cbbc9c4658bf5484b5159357adb5ef2d2094f9774eb33108e0edaac44aedcb36f

test:
  secret_key_base: 64b861bc31595e421fea7ae6209d8c3dd5ee7ee9e24763ee3b3fa88d13a63e59aefd9c74068d02c5f5a6a96953e387a8264aea16e2c8a3970791fcbdbfc84005

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
